version: '3.8'

services:
  db-staging:
    image: postgres:15
    container_name: postgres_catalogo_staging
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalogo_db_staging
    ports:
      - "5435:5432"
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data
    networks:
      - catalogo-staging

  api-staging:
    image: catalogo-backend:latest
    container_name: catalogo-backend-staging
    ports:
      - "8081:8080"
    depends_on:
      - db-staging
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-staging:5432/catalogo_db_staging
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: staging
    networks:
      - catalogo-staging
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data_staging:

networks:
  catalogo-staging:
    driver: bridge